# Generated by Django 2.2 on 2019-04-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_data', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
